### ISSUE TITLE
Uncaught TypeError: The "path" argument must be one of type string, Buffer, or URL. Received type...

### ISSUE THREAD

**Issue by hsb0407** [dsone/remote-ssh#7] opened 2020-05-21 02:14 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-SSH](https://github.com/dsone/remote-ssh) package 0.11.0

### Stack Trace

Uncaught TypeError: The "path" argument must be one of type string, Buffer, or URL. Received type boolean

```
At internal/fs/utils.js:423

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type boolean
    at Object.open (fs.js:418:3)
    at Object.module.(anonymous function) [as open] (electron/js2c/asar.js:161:31)
    at Object.writeFile (fs.js:1224:6)
    at /packages/Remote-SSH/node_modules/fs-plus/lib/fs-plus.js:300:21
    at /packages/Remote-SSH/node_modules/mkdirp/index.js:49:26
    at FSReqCallback.oncomplete (fs.js:164:5)
```

### Commands

```
     -0:24.8.0 remote-ssh:create-config (div.package-detail)
```

### Non-Core Packages

```
Remote-SSH 0.11.0 
```

**Comment by dsone** [comment] 2020-05-21 12:31
Duplicate of https://github.com/dsone/remote-ssh/issues/6.

**Closed as completed** 2021-02-14 21:25 UTC
Labels: bug, duplicate
